### ISSUE TITLE
Find out why the game is crashed

### ISSUE THREAD

**Issue by Craluminum2413** [Craluminum2413/MorePiles#1]
Added this part right into the `game:itemtypes/resource/bone.json` file:
```json
behaviors: [{ 
    name: "GroundStorable",
    properties: {
      layout: 'Stacking',
      placeRemoveSound: 'sounds/block/ceramicplace',
      stackingModel: 'morepiles:shapes/block/plant/bonepile',
      tessQuantityElements: 1,
      stackingCapacity: 128,
      transferQuantity: 1,
      bulkTransferQuantity: 8,
      collisionBox: { x1: 0, y1: 0, z1: 0, x2: 1, y2: 0.25, z2: 1 },
      cbScaleYByLayer: 0.1666666666666667
    }
  }],
```
Then game is crashed after trying to place bone on the ground:
```
Version: v1.15.1 (Stable)07/19/2021 01:03:35: Critical error occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: Unable to find a texture for texture code 'material' in storagePile. Giving up. Sorry.
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta)
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(String typeForLogging, Shape shapeBase, MeshData& modeldata, ITexPositionSource texSource, Vec3f wholeMeshRotation, Int32 generalGlowLevel, Byte climateColorMapId, Byte seasonColorMapId, Nullable`1 quantityElements, String[] selectiveElements)
   at Vintagestory.GameContent.BlockEntityGroundStorage.getOrCreateMesh(ItemSlot itemSlot, Vec3f offset)
   at Vintagestory.GameContent.BlockEntityGroundStorage.updateMeshes()
   at Vintagestory.GameContent.BlockEntityGroundStorage.OnPlayerInteract(IPlayer player, BlockSelection bs)
   at Vintagestory.GameContent.BlockGroundStorage.CreateStorage(IWorldAccessor world, BlockSelection blockSel, IPlayer player)
   at Vintagestory.GameContent.CollectibleBehaviorGroundStorable.Interact(ItemSlot itemslot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling, EnumHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass90_0.<OnHeldInteractStart>b__0(CollectibleBehavior bh, EnumHandling& hd)
   at Vintagestory.API.Common.CollectibleObject.WalkBehaviors(CollectibleBehaviorDelegate onBehavior, Action defaultAction)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _LpTdfLOAWwrFBtCzFbbeuEgj89qb._8DJtlEnHO7F1NYfVFrSNJNuDZpD(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._rmjRcUg6ZZy8gFclAtdmfo8RemC(Single )
   at _RWDpUP9pNIFCL1enbZzYqmh8eRe._uf2x7pSJniCpFh7nbMvuI5iHIsh(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _dWMiVfUAappivvjgQTrHbayLaP6._JCfAsRVSY5s6xyZG4pMiBR26lu(_mzzuiHzecediUg7OL4KPB2bLyPO , String[] )
   at _75U2lTywrsd0KIurOPIOvOxQoiH._JCfAsRVSY5s6xyZG4pMiBR26lu(ThreadStart )
```
I encountered this crash in the early pre-releases of 1.15: https://github.com/anegostudios/VintageStory-Issues/issues/937

**Comment by Craluminum2413** [comment]
Now it seems crash is fixed
```json
[
	{ file: "game:itemtypes/resource/bone", op: "add", path: "/behaviors",
		value: [ { name: "GroundStorable" } ] },

	{ file: "game:itemtypes/resource/bone", op: "add", path: "/behaviors/-", value: {
	name: "GroundStorable",
	properties: {
		layout: 'Stacking',
		placeRemoveSound: 'sounds/block/ceramicplace',
		stackingModel: 'morepiles:shapes/block/plant/bonepile',
		tessQuantityElements: 1,
		stackingCapacity: 128,
		transferQuantity: 1,
		bulkTransferQuantity: 8,
		collisionBox: { x1: 0, y1: 0, z1: 0, x2: 1, y2: 0.25, z2: 1 },
		cbScaleYByLayer: 0.1666666666666667
				}
		}
	},
]
```

**Comment by Craluminum2413** [comment]
Fixed and released first version
